<a href="https://colab.research.google.com/github/TejashwiniVadeghar/My-Projects/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [ ]:
df1=pd.read_csv('/content/drive/My Drive/Colab Notebooks/movies_dataset/credits.csv')
df2=pd.read_csv('/content/drive/My Drive/Colab Notebooks/movies_dataset/movies_metadata.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
df2.head()

   adult  ... vote_count
0  False  ...     5415.0
1  False  ...     2413.0
2  False  ...       92.0
3  False  ...       34.0
4  False  ...      173.0

[5 rows x 24 columns]

In [ ]:
df2['id']

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45461    439050
45462    111109
45463     67758
45464    227506
45465    461257
Name: id, Length: 45466, dtype: object

In [ ]:
df2 = df2[df2.id!='1997-08-20']
df2 = df2[df2.id!='2012-09-29']
df2 = df2[df2.id!='2014-01-01']

In [ ]:
df1.id

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45471    439050
45472    111109
45473     67758
45474    227506
45475    461257
Name: id, Length: 45476, dtype: int64

In [ ]:
df2['id'] = df2['id'].astype(int)

In [ ]:
df2.id

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45461    439050
45462    111109
45463     67758
45464    227506
45465    461257
Name: id, Length: 45463, dtype: int64

In [ ]:
df2=df2.merge(df1, on='id')

In [ ]:
df2.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [ ]:
df2['overview'].head()

0    Led by Woody, Andy's toys live happily in his ...
1    When siblings Judy and Peter discover an encha...
2    A family wedding reignites the ancient feud be...
3    Cheated on, mistreated and stepped on, the wom...
4    Just when George Banks has recovered from his ...
Name: overview, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(stop_words='english')
df2['overview'] = df2['overview'].fillna('')

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

In [ ]:
df2.head()

   adult  ...                                               crew
0  False  ...  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...
1  False  ...  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...
2  False  ...  [{'credit_id': '52fe466a9251416c75077a89', 'de...
3  False  ...  [{'credit_id': '52fe44779251416c91011acb', 'de...
4  False  ...  [{'credit_id': '52fe44959251416c75039ed7', 'de...

[5 rows x 26 columns]

In [ ]:
import random
ran = random.randint(25000, 30000)
df3 = df2.head(ran)
tfidf_matrix = tfidf.fit_transform(df3['overview'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape

(28290, 56653)

In [ ]:
print(tfidf_matrix)

  (0, 13792)	0.13810235208620703
  (0, 3337)	0.14831038405078886
  (0, 29004)	0.10225586287126369
  (0, 17028)	0.10394628680023062
  (0, 15302)	0.13458364255918961
  (0, 36798)	0.10419290893993716
  (0, 45074)	0.13159682117916155
  (0, 9530)	0.12900200273859141
  (0, 38734)	0.13390459882817796
  (0, 22603)	0.10459400623317189
  (0, 38581)	0.09425626190173929
  (0, 30070)	0.12074209783664473
  (0, 1452)	0.14697481051993389
  (0, 44369)	0.11643787733018848
  (0, 29504)	0.20103894708228284
  (0, 7523)	0.49666750520821673
  (0, 6899)	0.10825532474619087
  (0, 5664)	0.12580093792956312
  (0, 43167)	0.1136901353352995
  (0, 22230)	0.13458364255918961
  (0, 29749)	0.09002443533752454
  (0, 51376)	0.15416161014556454
  (0, 2413)	0.41770286652600325
  (0, 55565)	0.47257861811918034
  (0, 29043)	0.10906374319131583
  :	:
  (28288, 30963)	0.07947050281565071
  (28289, 43929)	0.1839305186093935
  (28289, 11222)	0.1839305186093935
  (28289, 46632)	0.367861037218787
  (28289, 19717)	0.1839305186093935
  (28289, 15439)	0.1839305186093935
  (28289, 34342)	0.1839305186093935
  (28289, 19702)	0.1839305186093935
  (28289, 18304)	0.1839305186093935
  (28289, 4637)	0.1839305186093935
  (28289, 5346)	0.1768663588052968
  (28289, 13214)	0.1768663588052968
  (28289, 26910)	0.34370851532075813
  (28289, 33771)	0.1768663588052968
  (28289, 49224)	0.1768663588052968
  (28289, 47019)	0.16479009785628237
  (28289, 19710)	0.17185425766037907
  (28289, 53824)	0.15772593805218563
  (28289, 40408)	0.3242088578862805
  (28289, 3593)	0.1679665699797002
  (28289, 36052)	0.1558903090306858
  (28289, 4530)	0.1447076984135652
  (28289, 16238)	0.2376229725840005
  (28289, 50820)	0.14296400819002908
  (28289, 18299)	0.11719904344717483

In [ ]:
print(tfidf_matrix[0])

  (0, 13792)	0.13810235208620703
  (0, 3337)	0.14831038405078886
  (0, 29004)	0.10225586287126369
  (0, 17028)	0.10394628680023062
  (0, 15302)	0.13458364255918961
  (0, 36798)	0.10419290893993716
  (0, 45074)	0.13159682117916155
  (0, 9530)	0.12900200273859141
  (0, 38734)	0.13390459882817796
  (0, 22603)	0.10459400623317189
  (0, 38581)	0.09425626190173929
  (0, 30070)	0.12074209783664473
  (0, 1452)	0.14697481051993389
  (0, 44369)	0.11643787733018848
  (0, 29504)	0.20103894708228284
  (0, 7523)	0.49666750520821673
  (0, 6899)	0.10825532474619087
  (0, 5664)	0.12580093792956312
  (0, 43167)	0.1136901353352995
  (0, 22230)	0.13458364255918961
  (0, 29749)	0.09002443533752454
  (0, 51376)	0.15416161014556454
  (0, 2413)	0.41770286652600325
  (0, 55565)	0.47257861811918034
  (0, 29043)	0.10906374319131583

In [ ]:
cosine_sim =  linear_kernel(tfidf_matrix, tfidf_matrix, True)

In [ ]:
cosine_sim.size

400000000

In [ ]:
print(cosine_sim)

[[1.         0.01578151 0.         ... 0.         0.         0.        ]
 [0.01578151 1.         0.04919425 ... 0.         0.         0.00956568]
 [0.         0.04919425 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.00956568 0.         ... 0.         0.         1.        ]]

In [ ]:
cosine_sim.shape

(20000, 20000)

In [ ]:
df3.head()

   adult  ...                                               crew
0  False  ...  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...
1  False  ...  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...
2  False  ...  [{'credit_id': '52fe466a9251416c75077a89', 'de...
3  False  ...  [{'credit_id': '52fe44779251416c91011acb', 'de...
4  False  ...  [{'credit_id': '52fe44959251416c75039ed7', 'de...

[5 rows x 26 columns]

In [ ]:
df3.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

In [ ]:
print(len(cosine_sim[0]))

20000

In [ ]:
indices = pd.Series(df3.index, index=df3['title']).drop_duplicates()

In [ ]:
df3.head()

   adult  ...                                               crew
0  False  ...  [{'credit_id': '52fe4284c3a36847f8024f49', 'de...
1  False  ...  [{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...
2  False  ...  [{'credit_id': '52fe466a9251416c75077a89', 'de...
3  False  ...  [{'credit_id': '52fe44779251416c91011acb', 'de...
4  False  ...  [{'credit_id': '52fe44959251416c75039ed7', 'de...

[5 rows x 26 columns]

In [ ]:
print(indices)

title
Toy Story                             0
Jumanji                               1
Grumpier Old Men                      2
Waiting to Exhale                     3
Father of the Bride Part II           4
                                  ...
Fearless Hyena Part II            19995
Recoil                            19996
Ghost Voyage                      19997
Peace, Love & Misunderstanding    19998
The Congress                      19999
Length: 20000, dtype: int64

In [ ]:
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df3['title'].iloc[movie_indices]

In [ ]:
get_recommendations('Assassins')

4857       The Blue Angel
18394     The Outside Man
14265             Kinatay
15307             Killers
17739          Colombiana
17355         Bad Teacher
9290          The Quickie
6386      Fulltime Killer
9274               Monday
8051     King of the Ants
Name: title, dtype: object

In [ ]:
get_recommendations('Toy Story')

15413               Toy Story 3
3008                Toy Story 2
10337    The 40 Year Old Virgin
8362                  The Champ
1080      Rebel Without a Cause
11444    For Your Consideration
1940                  Condorman
3068            Man on the Moon
485                      Malice
11651              Factory Girl
Name: title, dtype: object

In [ ]:
get_recommendations('Jumanji')

6195                       Brainscan
8836                         Quintet
17292                 The Dark Angel
9536                       Word Wars
13655    The Mindscape of Alan Moore
16912                         DeVour
8114                         Masques
6084                Poolhall Junkies
19798                 Wreck-It Ralph
2494                        eXistenZ
Name: title, dtype: object